#!/bin/bash

chmod +x /usr/local/bin/iot-object-workshop-monitoring/record/*
chmod +x /usr/local/bin/iot-object-workshop-monitoring/backup/*

systemctl enable monitoring-sd
systemctl enable monitoring-sd-config